name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 app.py downloader.py writers.py batch_transcribe.py \
            --max-line-length 120 \
            --extend-ignore E203,E266,W503 \
            --exclude .venv,downloads,outputs,.git,__pycache__

      - name: Batch script help
        run: python batch_transcribe.py --help
